-- BiblioSys Optimized Database Schema
-- Generated by PHP Architect/Backend Developer

CREATE DATABASE IF NOT EXISTS bibliosys CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bibliosys;

-- 1. Roles
CREATE TABLE roles (
    id_rol INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 2. Usuarios
CREATE TABLE usuarios (
    id_usuario INT AUTO_INCREMENT PRIMARY KEY,
    id_rol INT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles(id_rol) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 3. Autores
CREATE TABLE autores (
    id_autor INT AUTO_INCREMENT PRIMARY KEY,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    nacionalidad VARCHAR(100),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 4. Estudiantes
CREATE TABLE estudiantes (
    id_estudiante INT AUTO_INCREMENT PRIMARY KEY,
    carnet VARCHAR(30) NOT NULL UNIQUE,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    carrera VARCHAR(150) NOT NULL,
    correo VARCHAR(150),
    telefono VARCHAR(50),
    estado ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 5. Libros
CREATE TABLE libros (
    id_libro INT AUTO_INCREMENT PRIMARY KEY,
    codigo_libro VARCHAR(30) NOT NULL UNIQUE,
    isbn VARCHAR(30) NOT NULL UNIQUE,
    titulo VARCHAR(250) NOT NULL,
    id_autor INT NOT NULL,
    categoria VARCHAR(120),
    editorial VARCHAR(150),
    anio_publicacion INT,
    cantidad_total INT NOT NULL DEFAULT 1,
    cantidad_disponible INT NOT NULL DEFAULT 1,
    ubicacion VARCHAR(150) NOT NULL,
    estado ENUM('DISPONIBLE', 'PRESTADO', 'MANTENIMIENTO') NOT NULL DEFAULT 'DISPONIBLE',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_libro_autor FOREIGN KEY (id_autor) REFERENCES autores(id_autor) ON DELETE RESTRICT,
    CONSTRAINT chk_libro_cantidades CHECK (cantidad_total >= 0 AND cantidad_disponible >= 0 AND cantidad_disponible <= cantidad_total)
) ENGINE=InnoDB;

-- 6. Prestamos
CREATE TABLE prestamos (
    id_prestamo INT AUTO_INCREMENT PRIMARY KEY,
    id_estudiante INT NOT NULL,
    id_libro INT NOT NULL,
    fecha_prestamo DATE NOT NULL,
    fecha_devolucion_esperada DATE NOT NULL,
    fecha_devolucion_real DATE NULL,
    estado ENUM('ACTIVO', 'DEVUELTO') NOT NULL DEFAULT 'ACTIVO',
    observaciones TEXT,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_prestamo_estudiante FOREIGN KEY (id_estudiante) REFERENCES estudiantes(id_estudiante) ON DELETE RESTRICT,
    CONSTRAINT fk_prestamo_libro FOREIGN KEY (id_libro) REFERENCES libros(id_libro) ON DELETE RESTRICT,
    CONSTRAINT chk_prestamo_fechas CHECK (fecha_devolucion_esperada >= fecha_prestamo)
) ENGINE=InnoDB;

-- Indices for performance
CREATE INDEX idx_estudiantes_carnet ON estudiantes(carnet);
CREATE INDEX idx_libros_isbn ON libros(isbn);
CREATE INDEX idx_libros_estado ON libros(estado);
CREATE INDEX idx_prestamos_estado ON prestamos(estado);
CREATE INDEX idx_prestamos_estudiante ON prestamos(id_estudiante);
CREATE INDEX idx_prestamos_libro ON prestamos(id_libro);

-- Views for reporting (from BiblioSys)
CREATE OR REPLACE VIEW vw_usuarios_acceso AS
SELECT
    u.id_usuario,
    u.nombre,
    u.username,
    r.nombre AS rol,
    CASE WHEN u.activo = TRUE THEN 'ACTIVO' ELSE 'INACTIVO' END AS estado,
    CASE WHEN u.activo = TRUE THEN 'PUEDE_INGRESAR' ELSE 'SIN_ACCESO' END AS acceso
FROM usuarios u
INNER JOIN roles r ON r.id_rol = u.id_rol;

CREATE OR REPLACE VIEW vw_libros_disponibles AS
SELECT
    l.id_libro,
    l.codigo_libro,
    l.isbn,
    l.titulo AS libro,
    CONCAT(a.nombres, ' ', a.apellidos) AS autor,
    l.categoria,
    l.cantidad_disponible,
    l.ubicacion,
    l.estado
FROM libros l
INNER JOIN autores a ON a.id_autor = l.id_autor
WHERE l.activo = TRUE AND l.estado = 'DISPONIBLE' AND l.cantidad_disponible > 0;

CREATE OR REPLACE VIEW vw_prestamos_detalle AS
SELECT
    p.id_prestamo AS id,
    e.carnet,
    CONCAT(e.nombres, ' ', e.apellidos) AS estudiante,
    e.carrera,
    l.codigo_libro,
    l.isbn,
    l.titulo AS libro,
    CONCAT(a.nombres, ' ', a.apellidos) AS autor,
    l.ubicacion,
    p.fecha_prestamo AS prestamo,
    p.fecha_devolucion_esperada,
    p.fecha_devolucion_real AS fecha_devolucion,
    p.estado,
    p.observaciones
FROM prestamos p
INNER JOIN estudiantes e ON e.id_estudiante = p.id_estudiante
INNER JOIN libros l ON l.id_libro = p.id_libro
INNER JOIN autores a ON a.id_autor = l.id_autor;

CREATE OR REPLACE VIEW vw_historial_prestamos AS
SELECT
    id,
    carnet,
    estudiante,
    carrera,
    codigo_libro,
    isbn,
    libro,
    prestamo,
    fecha_devolucion_esperada,
    fecha_devolucion,
    estado
FROM vw_prestamos_detalle;
